# nonk8s
apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: task_queue
    jsonData:
      database: task_queue
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: task_queue
    isDefault: false
    editable: false
