spring.application.name=task-queue-sample
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_queue}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:task_queue}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:task_queue}
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

task.queue.partition-count=20
task.queue.worker-count=2
task.queue.runtime-enabled=true
task.queue.poll-batch-size=50
task.queue.poll-interval=250ms
task.queue.heartbeat-interval=1s
task.queue.heartbeat-task-timeout=3s
task.queue.process-timeout=10s
task.queue.heartbeat-deviation=3s
task.queue.dead-process-timeout-multiplier=3
task.queue.unregistration-action=REREGISTER
task.queue.stop-application-on-heartbeat-timeout=false
task.queue.cleanup-interval=1s
task.queue.cleanup-batch-size=32
task.queue.retry-max-attempts=3
task.queue.retry-backoff-strategy=EXPONENTIAL
task.queue.retry-initial-delay=5s
task.queue.retry-max-delay=5m
task.queue.retry-backoff-multiplier=2.0
task.queue.retry-jitter-factor=0.0
task.queue.retry-default-retryable=true
task.queue.retry-exception-traverse-causes=true
task.queue.rebalance-lock-key=584231947015
